[build]
  publish = "dist/"
  command = "npm run generate"

[[headers]]
for = "/*"

[headers.values]
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404